[package]
name = "layout-gen-previewer"
version = "0.1.0"
authors = ["Robin Mauritz <robin@mdev.co.id>"]
edition = "2024"
description = "Procedural macro derives for layout-gen"
license = "MIT OR Apache-2.0"
repository = "https://github.com/RoganMatrivski/layout-gen"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[target.'cfg(target_env = "musl")'.dependencies]
mimalloc = "^0.1.48"

[dependencies]
clap = { workspace = true, features = ["derive"] }
color-eyre = { workspace = true, features = ["capture-spantrace"] }
eyre = { workspace = true }
tracing = { workspace = true }
tracing-error = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

layout-gen = { workspace = true }
taffy = { workspace = true, features = ["parse"] }
eframe = { workspace = true }
notify = { workspace = true, features = ["flume"] }
random_color = { workspace = true }
flume = { workspace = true }
notify-debouncer-full = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
egui-toast = { workspace = true }
rfd = { workspace = true }
arboard = { workspace = true }
