[package]
name = "layout-gen-derive"
version = "0.1.0"
edition = "2024"
description = "Procedural macro derives for layout-gen"
license = "MIT OR Apache-2.0"
repository = "https://github.com/RoganMatrivski/layout-gen"

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["full"] }
quote = { workspace = true }
