[package]
name = "layout-gen-derive"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Procedural macro derives for layout-gen"

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["full"] }
quote = { workspace = true }
